name: Documentation Tests

on:
  push:
    paths:
      - 'doctests/**'
      - '.github/workflows/doctests.yml'
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  doctests:
    runs-on: ubuntu-latest
    services:
      redis-stack:
        image: redis/redis-stack-server:latest
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: lint check
        run: |
          pip install -r dev_requirements.txt
          pip install -r requirements.txt
          isort --check-only --diff doctests/*.py
          black --target-version py39 --check --diff doctests/*.py

      - name: run tests
        run: sh doctests/run_examples.sh
